---
- name: Download WaTTS for Ubuntu package
  get_url:
    url: "{{ deb_get_url }}"
    dest: "~/watts-latest.deb"
    force: yes
    # apt module has no option to ignore bad certificates
    validate_certs: no
  when: deb_get_url is defined

- block:
    - name: Install WaTTS for Ubuntu package
      apt:
        deb: "~/watts-latest.deb"
        state: present
        force: yes
      notify:
        - Restart WaTTS
      when: deb_get_url is defined
  rescue:
    # We need this because the above task (apt) runs `dpkg -i`,
    # which can not resolve dependecies
    - name: Resolve unmet dependencies
      command: apt-get -f install
