---
- name: Uninstall WaTTS for CentOS package
  yum:
    name: "{{ watts_pkg_name }}"
    state: absent
  when: rpm_get_url is defined

- name: Download/Install WaTTS for CentOS package
  yum:
    name: "{{ rpm_get_url }}"
    state: present
    validate_certs: no
  notify:
    - Restart WaTTS
  when: rpm_get_url is defined


- name: Install WaTTS package
  yum:
    name: "{{ watts_pkg_name }}"
    state: latest
    update_cache: yes
  when: rpm_get_url is undefined
